package com.carrotgarden.maven.scalor.scalanative

import java.io.File

import org.apache.maven.plugins.annotations.Parameter

import com.carrotgarden.maven.scalor.base
import com.carrotgarden.maven.tools.Description
import com.carrotgarden.maven.scalor.util.Folder
import com.carrotgarden.maven.scalor.util.Error.Throw

trait Build extends AnyRef
  with base.BuildAnyTarget
  with base.BuildAnyDependency
  with BuildAnyMode
  with BuildAnyRuntime {

}

trait BuildAnyMode {

  /**
   * Build mode for runtime release binary.
   */
  def nativeModeBuildRelease : String

  /**
   * Build mode for runtime debug binary.
   */
  def nativeModeBuildDebug : String

  def nativeBuildModeRelease : base.Mode.Type = {
    base.Mode.buildMode( nativeModeBuildRelease )
  }

  def nativeBuildModeDebug : base.Mode.Type = {
    base.Mode.buildMode( nativeModeBuildDebug )
  }

  def nativeHasBuildRelease( incremental : Boolean ) : Boolean = {
    base.Mode.hasBuildEnabled( nativeBuildModeRelease, incremental )
  }

  def nativeHasBuildDebug( incremental : Boolean ) : Boolean = {
    base.Mode.hasBuildEnabled( nativeBuildModeDebug, incremental )
  }

}

trait BuildAnyRuntime extends base.BuildAnyTarget {

  /**
   * Relative path of the generated runtime binary.
   */
  def nativeRuntimeDebug : String

  /**
   * Relative path of the generated runtime binary.
   */
  def nativeRuntimeRelease : String

  /**
   * Absolute path of the generated runtime binary.
   */
  def nativeRuntimeDebugFile : File = {
    val file = new File( buildTargetFolder, nativeRuntimeDebug ).getCanonicalFile
    Folder.ensureParent( file )
    file
  }

  /**
   * Absolute path of the generated runtime binary.
   */
  def nativeRuntimeReleaseFile : File = {
    val file = new File( buildTargetFolder, nativeRuntimeRelease ).getCanonicalFile
    Folder.ensureParent( file )
    file
  }

}

/**
 * Scala.native linker build parameters for scope=main.
 */
trait BuildMain extends Build
  with BuildMainDependency
  with BuildMainTarget
  with BuildMainMode
  with BuildMainRuntime {

}

trait BuildMainDependency extends base.BuildAnyDependency {

  @Description( """
  Folders with classes generated by current project and included in linker class path.
  Normally includes build output from scope=[macro,main]
  (<code>target/classes</code>).
  """ )
  @Parameter(
    property     = "scalor.nativeMainDependencyFolders",
    defaultValue = "${project.build.outputDirectory}"
  )
  var nativeMainDependencyFolders : Array[ File ] = Array.empty

  @Description( """
  Provide linker class path from project dependency artifacts based on these scopes.
  Scopes <a href="https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html">reference</a>.
  """ )
  @Parameter(
    property     = "scalor.nativeMainDependencyScopes",
    defaultValue = "provided"
  )
  var nativeMainDependencyScopes : Array[ String ] = Array.empty

  override def buildDependencyFolders = nativeMainDependencyFolders
  override def buildDependencyScopes = nativeMainDependencyScopes

}

trait BuildMainTarget extends base.BuildAnyTarget {

  @Description( """
  Build target directory for the generated runtime binary file with scope=main.
  """ )
  @Parameter(
    property     = "scalor.nativeMainTargetFolder",
    defaultValue = "${project.build.directory}/scalor/native/output/main"
  )
  var nativeMainTargetFolder : File = _

  override def buildTargetFolder = nativeMainTargetFolder

}

trait BuildMainMode extends BuildAnyMode {

  @Description( """
  Build mode for optimized <a href="#nativeMainRuntimeRelease"><b>nativeMainRuntimeRelease</b></a>.
  Normally uses <code>full</code>, to link only during Maven full build and skip Eclipse incremental build.
  Available build modes:
<pre>
  always - link during both full and incremental build
  never  - do not produce runtime at all
  full   - link only during full build
  incr   - link only during incremental build
</pre>
  """ )
  @Parameter(
    property     = "scalor.nativeMainBuildModeRelease",
    defaultValue = "full"
  )
  var nativeMainBuildModeRelease : String = _

  @Description( """
  Build mode for non-optimized <a href="#nativeMainRuntimeDebug"><b>nativeMainRuntimeDebug</b></a>.
  Normally uses <code>always</code>, to link during both Maven full build and Eclipse incremental build.
  Available build modes:
<pre>
  always - link during both full and incremental build
  never  - do not produce runtime at all
  full   - link only during full build
  incr   - link only during incremental build
</pre>
  """ )
  @Parameter(
    property     = "scalor.nativeMainBuildModeDebug",
    defaultValue = "always"
  )
  var nativeMainBuildModeDebug : String = _

  override def nativeModeBuildRelease = nativeMainBuildModeRelease
  override def nativeModeBuildDebug = nativeMainBuildModeDebug

}

trait BuildMainRuntime extends BuildAnyRuntime {

  @Description( """
  Relative path of the generated runtime binary file for scope=main, mode=release.
  File is packaged inside <a href="#nativeMainTargetFolder"><b>nativeMainTargetFolder</b></a>
  """ )
  @Parameter(
    property     = "scalor.nativeMainRuntimeRelease",
    defaultValue = "release"
  )
  var nativeMainRuntimeRelease : String = _

  @Description( """
  Relative path of the generated runtime binary file for scope=main, mode=debug.
  File is packaged inside <a href="#nativeMainTargetFolder"><b>nativeMainTargetFolder</b></a>
  """ )
  @Parameter(
    property     = "scalor.nativeMainRuntimeDebug",
    defaultValue = "debug"
  )
  var nativeMainRuntimeDebug : String = _

  override def nativeRuntimeRelease = nativeMainRuntimeRelease
  override def nativeRuntimeDebug = nativeMainRuntimeDebug

}

/**
 * Scala.native linker build parameters for scope=test.
 */
trait BuildTest extends Build
  with BuildTestDependency
  with BuildTestTarget
  with BuildTestMode
  with BuildTestRuntime {

}

trait BuildTestMode extends BuildAnyMode {

  @Description( """
  Build mode for optimized <a href="#nativeTestRuntimeRelease"><b>nativeTestRuntimeRelease</b></a>.
  Normally uses <code>full</code>, to link only during Maven full build and skip Eclipse incremental build.
  Available build modes:
<pre>
  always - link during both full and incremental build
  never  - do not produce runtime at all
  full   - link only during full build
  incr   - link only during incremental build
</pre>
  """ )
  @Parameter(
    property     = "scalor.nativeTestBuildModeRelease",
    defaultValue = "full"
  )
  var nativeTestBuildModeRelease : String = _

  @Description( """
  Build mode for non-optimized <a href="#nativeTestRuntimeDebug"><b>nativeTestRuntimeDebug</b></a>.
  Normally uses <code>always</code>, to link during both Maven full build and Eclipse incremental build.
  Available build modes:
<pre>
  always - link during both full and incremental build
  never  - do not produce runtime at all
  full   - link only during full build
  incr   - link only during incremental build
</pre>
  """ )
  @Parameter(
    property     = "scalor.nativeTestBuildModeDebug",
    defaultValue = "always"
  )
  var nativeTestBuildModeDebug : String = _

  override def nativeModeBuildRelease = nativeTestBuildModeRelease
  override def nativeModeBuildDebug = nativeTestBuildModeDebug

}

trait BuildTestDependency extends base.BuildAnyDependency {

  @Description( """
  Folders with classes generated by current project and included in linker class path.
  Normally includes build output from scope=[macro,main,test] 
  (<code>target/test-classes</code>, <code>target/classes</code>).
  """ )
  @Parameter(
    property     = "scalor.nativeTestDependencyFolders",
    defaultValue = "${project.build.testOutputDirectory},${project.build.outputDirectory}"
  )
  var nativeTestDependencyFolders : Array[ File ] = Array.empty

  @Description( """
  Provide linker class path from project dependencies selected by these scopes.
  Scopes <a href="https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html">reference</a>.
  """ )
  @Parameter(
    property     = "scalor.nativeTestDependencyScopes",
    defaultValue = "provided,test"
  )
  var nativeTestDependencyScopes : Array[ String ] = Array.empty

  override def buildDependencyFolders = nativeTestDependencyFolders
  override def buildDependencyScopes = nativeTestDependencyScopes

}

trait BuildTestTarget extends base.BuildAnyTarget {

  @Description( """
  Build target directory for the generated runtime binary file with scope=test.
  """ )
  @Parameter(
    property     = "scalor.nativeTestTargetFolder",
    defaultValue = "${project.build.directory}/scalor/native/output/test"
  )
  var nativeTestTargetFolder : File = _

  override def buildTargetFolder = nativeTestTargetFolder

}

trait BuildTestRuntime extends BuildAnyRuntime {

  @Description( """
  Relative path of the generated runtime binary file for scope=test, mode=release.
  File is packaged inside <a href="#nativeTestTargetFolder"><b>nativeTestTargetFolder</b></a>
  """ )
  @Parameter(
    property     = "scalor.nativeTestRuntimeRelease",
    defaultValue = "release"
  )
  var nativeTestRuntimeRelease : String = _

  @Description( """
  Relative path of the generated runtime binary file for scope=test, mode=debug.
  File is packaged inside <a href="#nativeTestTargetFolder"><b>nativeTestTargetFolder</b></a>
  """ )
  @Parameter(
    property     = "scalor.nativeTestRuntimeDebug",
    defaultValue = "debug"
  )
  var nativeTestRuntimeDebug : String = _

  override def nativeRuntimeRelease = nativeTestRuntimeRelease
  override def nativeRuntimeDebug = nativeTestRuntimeDebug

}
